import React from "react";

const PrivacyPolicy: React.FC = () => {

  return (
    <div className="min-h-screen flex flex-col items-center p-6 bg-[#121212] text-gray-300">
      <div className="w-full max-w-5xl bg-[#1E1E1E] shadow-md rounded-md p-8">
        <h1 className="text-3xl font-bold text-center mb-6 text-[#FF6B6B]">
          Privacy Policy
        </h1>

        <p className="mb-4 text-gray-400 text-sm text-center">
          Last updated: 1st December, 2024
        </p>

        <p className="mb-6">
            This Privacy Policy describes our policies and procedures on the collection, use, and disclosure of your information when you use the Service and tells you about your privacy rights and how the law protects you. We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.
        </p>

        <h2 className="text-xl font-semibold mb-4 text-gray-200">
          Interpretation and Definitions
        </h2>

        <h3 className="text-lg font-medium mb-2">Interpretation</h3>
        <p className="mb-4">
          The words of which the initial letter is capitalised have meanings defined
           under the following conditions. The following definitions shall have the same meaning
            regardless of whether they appear in singular or in plural.
        </p>

        <h3 className="text-lg font-medium mb-2">Definitions</h3>
        <p className="mb-4">For the purposes of this Privacy Policy:</p>

        <ul className="list-disc pl-6 mb-6 space-y-2">
          <li>
            <strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.
          </li>
          <li>
            <strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
          </li>
          <li>
            <strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Nitrutsav.
          </li>
          <li>
            <strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.
          </li>
          <li>
            <strong>Country</strong> refers to: Orissa, India
          </li>
          <li>
            <strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.
          </li>
          <li>
            <strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.
          </li>
          <li>
            <strong>Service</strong> refers to the Website.
          </li>
          <li>
            <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analysing how the Service is used.
          </li>
          <li>
            <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
          </li>
          <li>
            <strong>Website</strong> refers to the official website of Nitrutsav.
          </li>
          <li>
            <strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
          </li>
        </ul>

        <h2 className="text-xl font-semibold mb-4 text-gray-200">
          Collecting and Using Your Personal Data
        </h2>

        <h3 className="text-lg font-medium mb-2">Types of Data Collected</h3>
        <h4 className="text-md font-medium mb-2">Personal Data</h4>
        <p className="mb-4">
          While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
        </p>

        <ul className="list-disc pl-6 mb-6 space-y-2">
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, State, Province, ZIP/Postal code, City</li>
        </ul>

        <h3 className="text-lg font-medium mb-2">Usage Data</h3>
        <p className="mb-6">
          Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data. When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data. We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
        </p>

        <h3 className="text-lg font-medium mb-2">Tracking Technologies and Cookies</h3>
        <p className="mb-4">
          We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyse Our Service. The technologies We use may include:
        </p>

        <ul className="list-disc pl-6 mb-6 space-y-2">
          <li>
            <strong>Cookies or Browser Cookies:</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, Our Service may use Cookies.
          </li>
          <li>
            <strong>Web Beacons:</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics.
          </li>
        </ul>

        <h3 className="text-lg font-medium mb-2">Use of Cookies</h3>
        <p className="mb-4">We use both Session and Persistent Cookies for the purposes set out below:</p>

        <ul className="list-disc pl-6 mb-6 space-y-2">
          <li>
            <strong>Necessary / Essential Cookies:</strong>
            <ul className="list-disc pl-6">
              <li>Type: Session Cookies</li>
              <li>Administered by: Us</li>
              <li>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services. </li>
            </ul>
          </li>
          <li>
            <strong>Cookies Policy / Notice Acceptance Cookies:</strong>
            <ul className="list-disc pl-6">
              <li>Type: Persistent Cookies</li>
              <li>Administered by: Us</li>
              <li>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</li>
            </ul>
          </li>
          <li>
            <strong>Functionality Cookies:</strong>
            <ul className="list-disc pl-6">
              <li>Type: Persistent Cookies</li>
              <li>Administered by: Us</li>
              <li>Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</li>
            </ul>
          </li>
        </ul>

        <h2 className="text-xl font-semibold mb-4 text-gray-200">
          Use of Your Personal Data
        </h2>
        <p className="mb-4">The Company may use Personal Data for the following purposes:</p>

        <ul className="list-disc pl-6 mb-6 space-y-2">
          <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
          <li>To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Services that are available to You as a registered user.</li>
          <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
          <li>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application&apos;s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
          <li>To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
          <li>To manage Your requests: To attend and manage Your requests to Us.</li>
          <li>For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganisation, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</li>
          <li>For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
        </ul>

        <h2 className="text-xl font-semibold mb-4 text-gray-200">
          Sharing of Your Personal Data
        </h2>
        <p className="mb-4">We may share Your personal information in the following situations:</p>

        <ul className="list-disc pl-6 mb-6 space-y-2">
          <li>With Service Providers to monitor and analyse the use of our Service.</li>
          <li>For business transfers during mergers, sales, or acquisitions.</li>
          <li>With Affiliates, requiring them to honour this Privacy Policy.</li>
          <li>With business partners to offer products, services, or promotions.</li>
          <li>With other users when You interact in public areas.</li>
          <li>With Your consent for any other purpose.</li>
        </ul>

        <div className="space-y-6">
        <div>
          <h2 className="text-xl font-semibold mb-4 text-gray-200">Retention of Your Personal Data</h2>
          <p>
            The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies. The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.
          </p>
        </div>

        <div>
          <h2 className="text-xl font-semibold mb-4 text-gray-200">Transfer of Your Personal Data</h2>
          <p>
            Your information, including Personal Data, is processed at the Company&apos;s operating offices and in any other places where the parties involved in the processing are located. This information may be transferred to — and maintained on — computers located outside of Your state, province, country, or other governmental jurisdiction where data protection laws may differ from those in Your jurisdiction. Your consent to this Privacy Policy, followed by Your submission of such information, represents Your agreement to that transfer. The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy. No transfer of Your Personal Data will take place to an organisation or country unless there are adequate controls in place, including the security of Your data and other personal information.
          </p>
        </div>

        <div>
          <h2 className="text-xl font-semibold mb-4 text-gray-200">Delete Your Personal Data</h2>
          <p>
            You have the right to delete or request assistance in deleting the Personal Data we have collected about you. Our Service may allow you to delete certain information from within the Service. You may update, amend, or delete your information at any time by signing in to your Account and accessing the settings. You may also contact us to request access to, correct, or delete any personal information provided. However, we may retain certain information when we have a legal obligation or lawful basis to do so.
          </p>
        </div>

        <div>
          <h2 className="text-xl font-semibold mb-4 text-gray-200">Disclosure of Your Personal Data</h2>
          <p>
            In cases of business transactions, such as mergers, acquisitions, or asset sales, your Personal Data may be transferred with notice. Under specific conditions, such as legal requests from public authorities or to protect company rights, prevent wrongdoing, or ensure public safety, we may disclose your data in good faith. Such actions may be required to comply with legal obligations, defend company rights, or protect user safety and liability.
          </p>
        </div>

        <div>
          <h2 className="text-xl font-semibold mb-4 text-gray-200">Security of Your Personal Data</h2>
          <p>
            We prioritize the security of your data, employing commercially acceptable methods for protection. However, please note that no method of internet transmission or electronic storage can guarantee absolute security. While we take steps to protect your information, we cannot ensure it will be fully secure.
          </p>
        </div>

        <div>
          <h2 className="text-xl font-semibold mb-4 text-gray-200">Children’s Privacy</h2>
          <p>
            Our Service is not directed to anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under this age. If you are a parent or guardian and discover that your child has provided us with Personal Data, please contact us. We will take steps to remove that data from our servers. If parental consent is legally required in your country, we may require this consent before collecting and using such information.
          </p>
        </div>

        <div>
          <h2 className="text-xl font-semibold mb-4 text-gray-200">Links to Other Websites</h2>
          <p>
            Our Service may contain links to external websites not operated by us. If you click on a third-party link, you will be directed to that third-party’s site. We strongly advise you to review the Privacy Policy of every site you visit, as we have no control over, and are not responsible for, the content, privacy policies, or practices of these third-party sites or services.
          </p>
        </div>

        <div>
          <h2 className="text-xl font-semibold mb-4 text-gray-200">Changes to This Privacy Policy</h2>
          <p>
            We may periodically update our Privacy Policy. We will notify you of changes by posting the new Privacy Policy on this page and sending you an email and/or a prominent notice on our Service before the change becomes effective. The “Last updated” date at the top of this Privacy Policy will also be revised. Changes to this Privacy Policy are effective when posted. Please review this Privacy Policy regularly for any updates.
          </p>
        </div>

        <div>
            <h2 className="text-xl font-semibold mb-4 text-gray-200">
            Contact Us
            </h2>
            <p>
            If you have any questions about this Privacy Policy, please contact us by email at{" "}
            <a
                href="mailto:contact@nitrutsav.com"
                className="text-[#FF6B6B] hover:underline"
            >
                contact@nitrutsav.com
            </a>
            .
            </p>
        </div>
      </div>

        
      </div>
    </div>
  );
};

export default PrivacyPolicy;